// @ts-check
import { readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { packageFile } from './paths.js';
import { ensureFile } from './fs-safe.js';

export const MARKER = '// Generated by @seira-icons/ionicons — do not edit.';
export const MARKER_TOKEN = '// Generated by @seira-icons/ionicons';

/**
 * @param {string} src
 * @returns {Map<string,string>} kebab → Pascal
 */
export function parseExportMap(src) {
  const map = new Map();
  const re = /^export \{ default as (\w+) \} from '\.\/([\w-]+)';$/;
  for (const line of src.split('\n')) {
    const m = re.exec(line);
    if (m) map.set(m[2], m[1]);
  }
  if (map.size < 1000) {
    throw new Error(`export map parse collapsed (${map.size} entries) — package icons/index.ts format changed`);
  }
  return map;
}

/** @type {Map<string,string>|null} */
let _map = null;
/** @returns {Map<string,string>} */
export function exportNameMap() {
  if (!_map) _map = parseExportMap(packageFile('icons/index.ts'));
  return _map;
}

/**
 * @param {string[]} iconBasenames
 * @param {{hasTypes: boolean}} opts
 * @returns {string}
 */
export function buildBarrel(iconBasenames, { hasTypes }) {
  const map = exportNameMap();
  const lines = [MARKER];
  if (hasTypes) lines.push(`export type { IconProps } from './icon.types';`);
  const known = iconBasenames
    .filter((n) => map.has(n))
    .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
  for (const n of known) {
    lines.push(`export { default as ${map.get(n)} } from './${n}';`);
  }
  return `${lines.join('\n')}\n`;
}

/** @param {string} existing @returns {boolean} */
export function isManaged(existing) {
  const firstLine = existing.replace(/^﻿/, '').split('\n', 1)[0].replace(/\r$/, '').trimEnd();
  return firstLine.startsWith(MARKER_TOKEN);
}

/** @param {string} s @returns {string} */
function normalizeEol(s) {
  return s.replace(/\r\n/g, '\n');
}

/**
 * @param {string} realDir  already confined by the caller
 * @returns {{status: 'written'|'skipped-identical'|'skipped-unmanaged', count: number}}
 */
export function ensureBarrel(realDir) {
  const map = exportNameMap();
  let basenames;
  try {
    basenames = readdirSync(realDir)
      .filter((f) => f.endsWith('.tsx'))
      .map((f) => f.slice(0, -'.tsx'.length));
  } catch {
    return { status: 'skipped-unmanaged', count: 0 };
  }
  const known = basenames.filter((n) => map.has(n));
  const hasTypes = existsSync(join(realDir, 'icon.types.ts'));
  const content = buildBarrel(known, { hasTypes });
  let status;
  try {
    status = ensureFile(join(realDir, 'index.ts'), content, {
      compare: normalizeEol,
      allowOverwrite: isManaged,
    });
  } catch {
    // symlinked / EISDIR / unreadable index.ts — never followed/clobbered; downgrade, don't fail the add
    return { status: 'skipped-unmanaged', count: known.length };
  }
  return {
    status: status === 'conflict' ? 'skipped-unmanaged' : status,
    count: known.length,
  };
}
